"""add_map_confidence_and_clause

Revision ID: b03f6654a9d0
Revises: 4c5ade165605
Create Date: 2026-06-16 15:28:01.209994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = 'b03f6654a9d0'
down_revision: Union[str, None] = '4c5ade165605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maps', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('maps', sa.Column('source_clause', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maps', 'source_clause')
    op.drop_column('maps', 'confidence_score')
    # ### end Alembic commands ###
